/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NewRouteImport } from './routes/new'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceLabIdRouteImport } from './routes/workspace.$labId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceLabIdRoute = WorkspaceLabIdRouteImport.update({
  id: '/workspace/$labId',
  path: '/workspace/$labId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/labs': typeof LabsRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/workspace/$labId': typeof WorkspaceLabIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/labs': typeof LabsRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/workspace/$labId': typeof WorkspaceLabIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/labs': typeof LabsRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/workspace/$labId': typeof WorkspaceLabIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/labs' | '/new' | '/settings' | '/workspace/$labId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/labs' | '/new' | '/settings' | '/workspace/$labId'
  id: '__root__' | '/' | '/labs' | '/new' | '/settings' | '/workspace/$labId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabsRoute: typeof LabsRoute
  NewRoute: typeof NewRoute
  SettingsRoute: typeof SettingsRoute
  WorkspaceLabIdRoute: typeof WorkspaceLabIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$labId': {
      id: '/workspace/$labId'
      path: '/workspace/$labId'
      fullPath: '/workspace/$labId'
      preLoaderRoute: typeof WorkspaceLabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabsRoute: LabsRoute,
  NewRoute: NewRoute,
  SettingsRoute: SettingsRoute,
  WorkspaceLabIdRoute: WorkspaceLabIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
